// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.2
// source: fmGrpc/fm_bot.proto

package fmGrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 定义请求和响应的message类型
type BotCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CollectionId int64  `protobuf:"varint,1,opt,name=collectionId,proto3" json:"collectionId,omitempty"`
	MakerAddress string `protobuf:"bytes,2,opt,name=makerAddress,proto3" json:"makerAddress,omitempty"`
	Prompt       string `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`
}

func (x *BotCreateRequest) Reset() {
	*x = BotCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fmGrpc_fm_bot_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BotCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotCreateRequest) ProtoMessage() {}

func (x *BotCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fmGrpc_fm_bot_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotCreateRequest.ProtoReflect.Descriptor instead.
func (*BotCreateRequest) Descriptor() ([]byte, []int) {
	return file_fmGrpc_fm_bot_proto_rawDescGZIP(), []int{0}
}

func (x *BotCreateRequest) GetCollectionId() int64 {
	if x != nil {
		return x.CollectionId
	}
	return 0
}

func (x *BotCreateRequest) GetMakerAddress() string {
	if x != nil {
		return x.MakerAddress
	}
	return ""
}

func (x *BotCreateRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type BotCreateReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *BotCreateReply) Reset() {
	*x = BotCreateReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fmGrpc_fm_bot_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BotCreateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotCreateReply) ProtoMessage() {}

func (x *BotCreateReply) ProtoReflect() protoreflect.Message {
	mi := &file_fmGrpc_fm_bot_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotCreateReply.ProtoReflect.Descriptor instead.
func (*BotCreateReply) Descriptor() ([]byte, []int) {
	return file_fmGrpc_fm_bot_proto_rawDescGZIP(), []int{1}
}

func (x *BotCreateReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type TokenVerifyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *TokenVerifyRequest) Reset() {
	*x = TokenVerifyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fmGrpc_fm_bot_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenVerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenVerifyRequest) ProtoMessage() {}

func (x *TokenVerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fmGrpc_fm_bot_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenVerifyRequest.ProtoReflect.Descriptor instead.
func (*TokenVerifyRequest) Descriptor() ([]byte, []int) {
	return file_fmGrpc_fm_bot_proto_rawDescGZIP(), []int{2}
}

func (x *TokenVerifyRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type TokenVerifyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserAddress string `protobuf:"bytes,1,opt,name=userAddress,proto3" json:"userAddress,omitempty"`
}

func (x *TokenVerifyReply) Reset() {
	*x = TokenVerifyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fmGrpc_fm_bot_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenVerifyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenVerifyReply) ProtoMessage() {}

func (x *TokenVerifyReply) ProtoReflect() protoreflect.Message {
	mi := &file_fmGrpc_fm_bot_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenVerifyReply.ProtoReflect.Descriptor instead.
func (*TokenVerifyReply) Descriptor() ([]byte, []int) {
	return file_fmGrpc_fm_bot_proto_rawDescGZIP(), []int{3}
}

func (x *TokenVerifyReply) GetUserAddress() string {
	if x != nil {
		return x.UserAddress
	}
	return ""
}

var File_fmGrpc_fm_bot_proto protoreflect.FileDescriptor

var file_fmGrpc_fm_bot_proto_rawDesc = []byte{
	0x0a, 0x13, 0x66, 0x6d, 0x47, 0x72, 0x70, 0x63, 0x2f, 0x66, 0x6d, 0x5f, 0x62, 0x6f, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x66, 0x6d, 0x47, 0x72, 0x70, 0x63, 0x22, 0x72, 0x0a,
	0x10, 0x42, 0x6f, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6d, 0x61, 0x6b,
	0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x6f,
	0x6d, 0x70, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70,
	0x74, 0x22, 0x28, 0x0a, 0x0e, 0x42, 0x6f, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x2a, 0x0a, 0x12, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x34, 0x0a, 0x10, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x75,
	0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x32, 0x94, 0x01,
	0x0a, 0x0a, 0x42, 0x6f, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3f, 0x0a, 0x09,
	0x42, 0x6f, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x18, 0x2e, 0x66, 0x6d, 0x47, 0x72,
	0x70, 0x63, 0x2e, 0x42, 0x6f, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x66, 0x6d, 0x47, 0x72, 0x70, 0x63, 0x2e, 0x42, 0x6f, 0x74,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x45, 0x0a,
	0x0b, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x12, 0x1a, 0x2e, 0x66,
	0x6d, 0x47, 0x72, 0x70, 0x63, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x66, 0x6d, 0x47, 0x72, 0x70,
	0x63, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x00, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x46, 0x75, 0x73, 0x69, 0x6f, 0x6e, 0x4d, 0x61, 0x74, 0x65, 0x2f, 0x66, 0x6d,
	0x2d, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x66, 0x6d, 0x47, 0x72, 0x70, 0x63, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_fmGrpc_fm_bot_proto_rawDescOnce sync.Once
	file_fmGrpc_fm_bot_proto_rawDescData = file_fmGrpc_fm_bot_proto_rawDesc
)

func file_fmGrpc_fm_bot_proto_rawDescGZIP() []byte {
	file_fmGrpc_fm_bot_proto_rawDescOnce.Do(func() {
		file_fmGrpc_fm_bot_proto_rawDescData = protoimpl.X.CompressGZIP(file_fmGrpc_fm_bot_proto_rawDescData)
	})
	return file_fmGrpc_fm_bot_proto_rawDescData
}

var file_fmGrpc_fm_bot_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_fmGrpc_fm_bot_proto_goTypes = []interface{}{
	(*BotCreateRequest)(nil),   // 0: fmGrpc.BotCreateRequest
	(*BotCreateReply)(nil),     // 1: fmGrpc.BotCreateReply
	(*TokenVerifyRequest)(nil), // 2: fmGrpc.TokenVerifyRequest
	(*TokenVerifyReply)(nil),   // 3: fmGrpc.TokenVerifyReply
}
var file_fmGrpc_fm_bot_proto_depIdxs = []int32{
	0, // 0: fmGrpc.BotService.BotCreate:input_type -> fmGrpc.BotCreateRequest
	2, // 1: fmGrpc.BotService.TokenVerify:input_type -> fmGrpc.TokenVerifyRequest
	1, // 2: fmGrpc.BotService.BotCreate:output_type -> fmGrpc.BotCreateReply
	3, // 3: fmGrpc.BotService.TokenVerify:output_type -> fmGrpc.TokenVerifyReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fmGrpc_fm_bot_proto_init() }
func file_fmGrpc_fm_bot_proto_init() {
	if File_fmGrpc_fm_bot_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_fmGrpc_fm_bot_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BotCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fmGrpc_fm_bot_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BotCreateReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fmGrpc_fm_bot_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokenVerifyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fmGrpc_fm_bot_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokenVerifyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fmGrpc_fm_bot_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fmGrpc_fm_bot_proto_goTypes,
		DependencyIndexes: file_fmGrpc_fm_bot_proto_depIdxs,
		MessageInfos:      file_fmGrpc_fm_bot_proto_msgTypes,
	}.Build()
	File_fmGrpc_fm_bot_proto = out.File
	file_fmGrpc_fm_bot_proto_rawDesc = nil
	file_fmGrpc_fm_bot_proto_goTypes = nil
	file_fmGrpc_fm_bot_proto_depIdxs = nil
}
